openapi: 3.1.0
info:
  title: todo
  description: ''
  version: 1.0.0
tags: []
paths:
  /todos:
    post:
      summary: create
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type:
                    - string
                    - 'null'
                priority:
                  type: string
                  default: low
                  enum:
                    - low
                    - medium
                    - high
              required:
                - title
                - priority
            example:
              title: test todo
              description: test description
              priority: medium
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type:
                      - string
                      - 'null'
                  status:
                    type: boolean
                    description: 상태
                  priority:
                    type: string
                    default: low
                    enum:
                      - low
                      - medium
                      - high
                  createdDt:
                    type: string
                    description: UTC TIME
                    format: date-time
                  updatedDt:
                    type: string
                    description: UTC TIME
                    format: date-time
                required:
                  - id
                  - title
                  - status
                  - priority
                  - createdDt
                  - updatedDt
              example:
                id: 1
                title: test todo
                description: test description
                status: false
                priority: medium
                createdDt: '2026-03-08T12:33:09.061367'
                updatedDt: '2026-03-08T12:33:09.061379'
          headers: {}
        '422':
          $ref: '#/components/responses/422Response'
          description: ''
      security: []
    get:
      summary: gets
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: page
          in: query
          description: ''
          required: false
          example: 0
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: ''
          required: false
          example: 100
          schema:
            type: integer
            default: 100
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        description:
                          type:
                            - string
                            - 'null'
                        status:
                          type: boolean
                          description: 상태
                        priority:
                          type: string
                          default: low
                          enum:
                            - low
                            - medium
                            - high
                        createdDt:
                          type: string
                          description: UTC TIME
                          format: date-time
                        updatedDt:
                          type: string
                          description: UTC TIME
                          format: date-time
                      required:
                        - id
                        - title
                        - status
                        - priority
                        - createdDt
                        - updatedDt
                  metadata:
                    type: object
                    properties:
                      page:
                        type: integer
                      size:
                        type: integer
                      totalCount:
                        type: integer
                      hasNext:
                        type: boolean
                    required:
                      - page
                      - size
                      - totalCount
                      - hasNext
                required:
                  - data
                  - metadata
          headers: {}
        '422':
          $ref: '#/components/responses/422Response'
          description: ''
      security: []
  /todos/{todo_id}:
    get:
      summary: get
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: todo_id
          in: path
          description: ''
          required: true
          example: 1
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type:
                      - string
                      - 'null'
                  status:
                    type: boolean
                    description: 상태
                  priority:
                    type: string
                    default: low
                    enum:
                      - low
                      - medium
                      - high
                  createdDt:
                    type: string
                    description: UTC TIME
                    format: date-time
                  updatedDt:
                    type: string
                    description: UTC TIME
                    format: date-time
                required:
                  - id
                  - title
                  - status
                  - priority
                  - createdDt
                  - updatedDt
          headers: {}
        '422':
          $ref: '#/components/responses/422Response'
          description: ''
      security: []
    patch:
      summary: patch
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: todo_id
          in: path
          description: ''
          required: true
          example: 1
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type:
                    - string
                    - 'null'
                description:
                  type:
                    - string
                    - 'null'
                status:
                  type:
                    - boolean
                    - 'null'
                priority:
                  type:
                    - string
                    - 'null'
            examples: {}
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '422':
          $ref: '#/components/responses/422Response'
          description: ''
      security: []
    delete:
      summary: delete
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: todo_id
          in: path
          description: ''
          required: true
          example: 0
          schema:
            type: integer
      responses:
        '204':
          description: '204'
          headers: {}
        '422':
          $ref: '#/components/responses/422Response'
          description: ''
      security: []
webhooks: {}
components:
  schemas:
    TodoCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type:
            - string
            - 'null'
        priority:
          type: string
          default: low
          enum:
            - low
            - medium
            - high
      required:
        - title
        - priority
    TodoResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type:
            - string
            - 'null'
        status:
          type: boolean
          description: 상태
        priority:
          type: string
          default: low
          enum:
            - low
            - medium
            - high
        createdDt:
          type: string
          description: UTC TIME
          format: date-time
        updatedDt:
          type: string
          description: UTC TIME
          format: date-time
      required:
        - title
        - priority
        - id
        - createdDt
        - updatedDt
        - status
    TodoResponses:
      type: object
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              description:
                type:
                  - string
                  - 'null'
              status:
                type: boolean
                description: 상태
              priority:
                type: string
                default: low
                enum:
                  - low
                  - medium
                  - high
              createdDt:
                type: string
                description: UTC TIME
                format: date-time
              updatedDt:
                type: string
                description: UTC TIME
                format: date-time
            required:
              - id
              - title
              - status
              - priority
              - createdDt
              - updatedDt
        metadata:
          type: object
          properties:
            page:
              type: integer
            size:
              type: integer
            totalCount:
              type: integer
            hasNext:
              type: boolean
          required:
            - page
            - size
            - totalCount
            - hasNext
      required:
        - data
        - metadata
    TodoUpdate:
      type: object
      properties:
        title:
          type:
            - string
            - 'null'
        description:
          type:
            - string
            - 'null'
        status:
          type:
            - boolean
            - 'null'
        priority:
          type:
            - string
            - 'null'
    Todo422Response:
      type: object
      properties:
        detail:
          type:
            - array
            - 'null'
          items:
            type: object
            properties:
              type:
                type:
                  - string
                  - 'null'
              loc:
                type:
                  - array
                  - 'null'
                items:
                  type: string
              msg:
                type:
                  - string
                  - 'null'
              input:
                type:
                  - string
                  - 'null'
    PageMetadata:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        totalCount:
          type: integer
        hasNext:
          type: boolean
      required:
        - page
        - size
        - totalCount
        - hasNext
  responses:
    422Response:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type:
                        - string
                        - 'null'
                    loc:
                      type: 'null'
                    msg:
                      type: string
                    input:
                      type:
                        - string
                        - 'null'
                  required:
                    - type
                    - loc
                    - msg
                    - input
              type:
                type: string
            required:
              - detail
              - type
          examples:
            예시 1:
              summary: 예시 1
              value:
                detail:
                  - type: missing
                    loc:
                      - body
                    msg: Field required
                    input: null
  securitySchemes: {}
servers: []
security: []
